apiVersion: v1
kind: Secret
metadata:
  name: rstudio-postgresql
  namespace: {{ .Values.global.namespaces.rstudioPackageManager }}
type: Opaque
data:
  password: {{ .Values.global.postgresql.auth.password | b64enc }}