apiVersion: v1
kind: Secret
metadata:
  name: rstudio-license
  namespace: {{ .Values.global.namespaces.rstudioPackageManager }}
type: Opaque
data:
  rstudio-package-manager.lic: {{ .Values.global.pmLicense }}