{{- $claimMin := index .Values "rstudio-workbench" "hpa" "minReplicas" -}}
{{- $claimMax := index .Values "rstudio-workbench" "hpa" "maxReplicas" -}}
{{- $fullName := index .Values "rstudio-workbench" "fullnameOverride" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.global.namespaces.rstudioWorkbench }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  minReplicas: {{ $claimMin }}
  maxReplicas: {{ $claimMax }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
