environments:
  mvp-aks:
    values:
      - ./values-environments/mvp-aks/global.yaml
  mvp-gcp:
    values:
      - ./values-environments/mvp-gcp/global.yaml
---
repositories:
  - name: rstudio
    url: https://helm.rstudio.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: nfs-ganesha-server-and-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

helmDefaults:
  wait: true
  timeout: 600  

releases:
  - name: cert-manager
    namespace: cert-manager    
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.17.1
    values:
      - ./values-environments/{{ .Environment.Name }}/cert-manager.yaml

  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    wait: false
    version: 4.12.3
    values:
      - ./values-environments/{{ .Environment.Name }}/global.yaml
      - ./values-environments/{{ .Environment.Name }}/ingress-nginx.yaml
    needs:
      - cert-manager/cert-manager

  - name: kimbodo-posit-base-resources
    namespace: kimbodo-posit
    createNamespace: true
    chart: ./posit
    version: 0.0.1
    values:
      - ./values-environments/{{ .Environment.Name }}/global.yaml
    needs:
      - cert-manager/cert-manager

  - name: postgresql
    namespace: postgresql
    createNamespace: false
    chart: bitnami/postgresql
    version: 11.6.16
    values:
      - ./values-environments/{{ .Environment.Name }}/global.yaml
      - ./values-environments/{{ .Environment.Name }}/postgresql.yaml
    needs:
      - kimbodo-posit/kimbodo-posit-base-resources

  - name: postgresql-package-manager
    namespace: postgresql
    createNamespace: false
    chart: bitnami/postgresql
    version: 11.6.16
    values:      
      - ./values-environments/{{ .Environment.Name }}/postgresql-package-manager.yaml
    needs:
      - kimbodo-posit/kimbodo-posit-base-resources

  - name: nfs-server-provisioner
    namespace: nfs-server-provisioner
    createNamespace: false
    chart: nfs-ganesha-server-and-external-provisioner/nfs-server-provisioner
    version: 1.8.0
    values:
      - ./values-environments/{{ .Environment.Name }}/global.yaml
      - ./values-environments/{{ .Environment.Name }}/nfs-server-provisioner.yaml
    needs:
      - kimbodo-posit/kimbodo-posit-base-resources

  - name: rstudio-connect
    namespace: rstudio-connect
    createNamespace: false
    chart: rstudio/rstudio-connect
    version: 0.8.3
    values:
      - ./values-environments/{{ .Environment.Name }}/global.yaml
      - ./values-environments/{{ .Environment.Name }}/rstudio-connect.yaml
    needs:
      - kimbodo-posit/kimbodo-posit-base-resources
      - nfs-server-provisioner/nfs-server-provisioner
      - postgresql/postgresql

  - name: rstudio-workbench
    namespace: rstudio-workbench
    createNamespace: false
    chart: rstudio/rstudio-workbench
    version: 0.9.6
    values:
      - ./values-environments/{{ .Environment.Name }}/global.yaml
      - ./values-environments/{{ .Environment.Name }}/rstudio-workbench.yaml
    needs:
      - kimbodo-posit/kimbodo-posit-base-resources
      - nfs-server-provisioner/nfs-server-provisioner
      - postgresql/postgresql

  - name: rstudio-package-manager
    namespace: rstudio-package-manager
    createNamespace: false
    chart: rstudio/rstudio-pm
    version: 0.5.48
    values:
      - ./values-environments/{{ .Environment.Name }}/global.yaml
      - ./values-environments/{{ .Environment.Name }}/rstudio-package-manager.yaml
    needs:
      - kimbodo-posit/kimbodo-posit-base-resources
      - nfs-server-provisioner/nfs-server-provisioner
      - postgresql/postgresql
      - postgresql/postgresql-package-manager
