## @@ Section GLOBAL ##
global:
  oauth2:
    connectUrl:
    client:
      id:
      secret:
  # -- clusterIssuer is the object to set properties to thee issuer that calls letsencrypt
  clusterIssuer:
    # -- enbled is if we gonna create it or not
    enabled: true
    # -- name is the letscrypt metadaname
    name: letsencrypt-prod
    # -- email is required by letsencrypt
    email: 
    # -- server is the lesencrypt server to get the cert. Default value is prod
    server: https://acme-v02.api.letsencrypt.org/directory
    # -- accountKeySecret is the metadaname of the key generated 
    accountKeySecret: letsencrypt-prod-account-key

  # -- postresql section is used by postgresql chart
  postgresql:
    # -- auth is the object that postgre creat at the first execution
    auth:      
      # username is the username to be created
      username: 
      # password is the password for this user
      password: 
      # database is one database to bee created at the first execution
      database: 

## @@ Section Network File System
# -- nsf is need to scale rstudio-connect 
nfs-server-provisioner:
  persistence:
    enabled: true
    size: "50Gi"
  storageClass:
    name: rsc-nfs
    mountOptions:
      - vers=4

## @@ Section NGINX
ingress-nginx:
  controller:
    service:
      ## Ingress IP
      loadBalancerIP: 
    publishService:
      enabled: true
    config:
      strict-validate-path-type: false

## @@ Section RStudio-connect
rstudio-connect:
  # -- Host to ingress posit-connect
  ingressHost: 
  # Configures shared storage for the Posit Connect pod.
  sharedStorage:
    # -- mount true means that the PVC is already created.
    # -- in our environment we always gonna create it before apply the rstudio-connect chart
    # -- or use a cloud storage, but never keep to rstudio create it
    mount: true

    # The name of the PVC created for Connect's data directory.
    # Also specified by `Launcher.DataDirPVCName` below.
    name: rsc-pvc

    # The storageClass to use for Connect's data directory. Must
    # support RWX.
    # Replace with your storage class name if different.
    storageClassName: rsc-nfs
    requests:
      storage: 10G
  
  # -- Defines resources for the rstudio-connect container
  # -- Default valuess is for a MVP
  resources: 
    requests:
      memory: "128Mi"
      cpu: "100m"      
    limits:
      memory: "2Gi"
      cpu: "2000m"      
  
  # -- HPA define how much repelpicas we will have for rstudio-connect pod
  hpa:
    minReplicas: 1
    maxReplicas: 5

  # -- PDB enabled without any more configuration keep at least 1 up
  pdb:
    enabled: true

  # -- Config section is used to create a configuration file readed by rstudio-connect pod
  # -- the file structure is>
  # ```
  # [OAuth2]
  #  AllowedDomain = kimbodo.com
  # [Database]
  #   Provider = Poostgres
  # ````
  config:
    # set the database to use
    Database:
      Provider: "Postgres"
    # Postgres basic config  
    Postgres:
      URL: "postgres://connect@kimbodo-posit-postgresql.kimbodo-posit.svc.cluster.local:5432/connect?sslmode=disable"
    # Authentication type
    Authentication:
      Provider: "oauth2"
    # Here is important to fill the domain, Id and secreet to validade the OAuth
    OAuth2:
      ClientId: 
      ClientSecret:
      AllowedDomain: 

  # -- pod properties to add to rstudio-connect pod
  pod:
    env:
      - name: CONNECT_POSTGRES_PASSWORD
        valueFrom:
          # -- this secret is created by postgresql chart
          secretKeyRef:
            name: kimbodo-posit-postgresql
            key: password    

rstudio-workbench:  
  userCreate: true
  # -- Host to ingress posit-connect
  ingressHost: 
  # -- HPA define how much repelpicas we will have for rstudio-connect pod
  hpa:
    minReplicas: 1
    maxReplicas: 5

  # Mounts the license file appropriately from the Secret
  # license:
  #   file:
  #     # Replace with the name of your license file secret and key
  #     secret: rstudio-workbench-license
  #     secretKey: rstudio-workbench.lic

  # Configures user home directory shared storage
  homeStorage:
    create: true
    # The name of the PVC created for Workbench's user home directory shared storage.
    name: workbench-user-pvc
    # The storageClass to use for Workbench's user home directory. Must support RWX.
    # Replace with your storage class name.
    storageClassName: rsc-nfs
    requests:
      storage: 10G

  # Configures Workbench shared storage
  sharedStorage:
    create: true
    # The name of the PVC created for Workbench's shared storage directory.
    name: workbench-shared-pvc

    # The storageClass to use for Workbench's shared storage directory. Must support RWX.
    # Replace with your storage class name.
    storageClassName: rsc-nfs
    requests:
      storage: 1G

  # Adds an environment variable containing the PostgreSQL password from a Secret
  pod:
    extraVolumes:
      - name: rstudio-run
        emptyDir: {}
    extraVolumeMounts:
      - name: rstudio-run
        mountPath: /var/run/rstudio-server/rstudio-rserver
    env:
      - name: WORKBENCH_POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            # Replace with the name of your database password secret and key
            name: kimbodo-posit-postgresql
            key: password      
  # Creates a test user to verify installation
  userCreate: true

  # The config section is converted into the correct configuration files and are
  # mounted to the server/session pods as needed.
  config:
    
    secret:
      database.conf:
        provider: "postgresql"
        connection-uri: "postgres://connect@kimbodo-posit-postgresql.kimbodo-posit.svc.cluster.local:5432/connect?sslmode=disable"
        # While it is possible to set a Postgres password here in the values file,
        # we recommend adding it from a Secret as an environment variable as shown in pod.env
      openid-client-secret:
        client-id: 
        client-secret: 
    session:
      rsession.conf:
        # These settings apply to RStudio Pro IDE sessions
        session-timeout-minutes: 60
        session-timeout-suspend: 1
        session-quit-child-processes-on-exit: 1
      repos.conf:
        # This will set the Posit Public Package Manager (P3M) as the default R repository
        # for Workbench users. This is recommended as P3M provides linux binaries for many
        # R packages which will decrease package installation time. If you have your own
        # Posit Package Manager server then replace these URLs with the URLs of your server.
        CRAN: https://packagemanager.posit.co/cran/__linux__/jammy/latest
    server:
      rserver.conf:
        auth-openid: "1"
        auth-openid-issuer:
        auth-openid-username-claim: given_name
      jupyter.conf:
        # These settings apply to Jupyter Notebook and JupyterLab IDE sessions
        session-cull-minutes: 60
        session-shutdown-minutes: 5
    profiles:
      launcher.kubernetes.profiles.conf:
        "*":
          # These settings are applied for all users and can be changed to suit
          # your particular user needs. See the following resources for more information:
          # https://github.com/rstudio/helm/tree/main/charts/rstudio-workbench#etcrstudiolauncherkubernetesprofilesconf
          # https://docs.posit.co/ide/server-pro/job_launcher/kubernetes_plugin.html#kube-profiles
          default-cpus: "1.0"
          default-mem-mb: "2048"
          max-cpus: "4.0"
          max-mem-mb: "8192"
