## @@ Section GLOBAL ##
global:
  namespaces:
    rstudioConnect: rstudio-connect
    rstudioWorkbench: rstudio-workbench
    rstudioPackageManager: rstudio-package-manager
    postgresql: postgresql
    nfsServerProvisioner: nfs-server-provisioner

  # -- workbench license in base64
  wbLicense: 
  # -- connect license in base64
  ctLicense: 

  # -- clusterIssuer is the object to set properties to thee issuer that calls letsencrypt
  clusterIssuer:
    # -- enbled is if we gonna create it or not
    enabled: true
    # -- name is the letscrypt metadaname
    name: letsencrypt-prod
    # -- email is required by letsencrypt
    email: 
    # -- server is the lesencrypt server to get the cert. Default value is prod
    server: https://acme-v02.api.letsencrypt.org/directory
    # -- accountKeySecret is the metadaname of the key generated 
    accountKeySecret: letsencrypt-prod-account-key

  # -- postresql section is used by postgresql chart
  postgresql:
    # -- auth is the object that postgre creat at the first execution
    auth:      
      # username is the username to be created
      username: 
      # password is the password for this user
      password: 
      # database is one database to bee created at the first execution
      database: 
