{{- if .Values.global.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.global.clusterIssuer.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  acme:
    email: {{ .Values.global.clusterIssuer.email }}
    server: {{ .Values.global.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.global.clusterIssuer.accountKeySecret }}
    solvers:
      - http01:
          ingress:
            class: nginx
{{- end }}
