{{- $claimMin := index .Values "rstudio-connect" "hpa" "minReplicas" -}}
{{- $claimMax := index .Values "rstudio-connect" "hpa" "maxReplicas" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: posit-connect-hpa
  namespace: {{ .Release.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: posit-connect-rstudio-connect
  minReplicas: {{ $claimMin }}
  maxReplicas: {{ $claimMax }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
